name: 'Deploy'

on:
  pull_request:
  push:
    branches: [master]

env:
  REACT_APP_ATILA_STAGE: prod

jobs:
  deploy:
    name: 'Deploy'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - run: NODE_ENV="production" npm install
      - run: npm run build
      - name: Deploy to netlify prod environment
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID_PROD }}
          REACT_APP_ATILA_STAGE: prod
        with:
          args: deploy --dir=./build --prod -m "${{github.ref_name}} ${{github.sha}}"
      - name: Deploy to netlify staging site
        if: ${{ github.ref != 'refs/heads/master' }}
        uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID_STAGING }}
          REACT_APP_ATILA_STAGE: staging
        with:
          args: deploy --dir=./build --prod -m "${{github.ref_name}} ${{github.sha}}"